raven_website_v1/forms.py
"""
This script contains all the form templates to be used in html files.
All feilds require a label. The label is Just the name/string/text associated with that feild on the html page
"""
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, EmailField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo

class loginForm(FlaskForm):
    email = EmailField(label="Email", validators=[DataRequired(), Email()])
    password = PasswordField(label="password", validators=[DataRequired()])
    rememberMe = BooleanField(label="Remember Me")
    submit = SubmitField(label="Sign In")
    createAccount = SubmitField(label="Create Accont")
    forgotPassword = SubmitField(label="Forgot Password")

    def validate(self, email:str):
        #this is where login should be validated. curently being done in views.py under helper functions
        pass

class createAccountForm(FlaskForm):
    userName = StringField(label="Username", validators=[DataRequired(), Length(min=2, max=20)])
    email = EmailField(label="Email", validators=[DataRequired(), Email()])
    password = PasswordField(label="Password", validators=[DataRequired()])
    passowrdConfirm = PasswordField(label="Confirm Password", validators=[DataRequired(), EqualTo("password")])
    submit = SubmitField(label="Create Account")

    def validate(self, email):
        #this is whwere new accounts should be validated. it is curently being done in views.py under helper functions
        pass

class profileForm(FlaskForm):
    knowledge = StringField(label="knowledge")
    instruction = StringField(label="instruction")
    submit = SubmitField(label="Add Info")

class chatForm(FlaskForm):
    chat1 = StringField(label="Message Chat", validators=[DataRequired()]) #the main chat box
    chat2 = StringField(label="Knowledge Base") #secondary chat box for extra information
    chat3 = StringField(label="Instructions") #terterary chat box for extra information
    modelName = StringField(label="Huggingface model name")
    submit = SubmitField(label="Enter")

raven_website_v1/app.py
#app.py
from flask import Flask, redirect, url_for
from views import views
from datetime import timedelta

app = Flask(__name__)
app.config["SECRET_KEY"] = "4rda8v0ecn477bbf8b7d3d96232037f53168f36c7addc44964e08f52478cb985006a7".encode("utf8") #this is just some random string
app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///site.db"
app.permanent_session_lifetime = timedelta(days=30) #sessions are saved for n days
app.register_blueprint(views, url_prefix="/")

if __name__ == "__main__":
    app.run(debug=True, port=8000)

raven_website_v1/views.py
"""
This files contains all the routesd to all the web pages.
"""
from flask import Blueprint, render_template, request, url_for, redirect, session, flash
from forms import loginForm, createAccountForm, chatForm
import database as db #custum sqlalchemy database
from sqlalchemy import Select
from huggingBot import huggingBot #custom hugging face api

views = Blueprint("views", import_name=__name__)
bcrypt = None #this has to be set by app.by to pass the encryption key
user = None #this user curetnly on the page
bot = huggingBot() #the active hugging face model
chatMessages = []

@views.route("/", methods = ["POST", "GET"])
def home():
    form = chatForm()
    username = "User"
    if user != None:
        username = user.username #if there as an active user, set the user name to that their name
    if form.is_submitted():
        addDataToUser(form.chat2.data, form.chat3.data)
        chatMessages.append(f"{username}: {form.chat1.data}") #need ot add username from user database
        botResponse = getBotResponse(form.modelName.data, form.chat3.data, form.chat2.data, username + form.chat1.data)
        chatMessages.append(f"Ravnn : {botResponse}")
        return redirect(url_for("views.home"))
    return render_template("chat.html", title="Home", chatMessages=chatMessages, form=form, user=user)

@views.route("/about")
def about():
    return render_template("about.html", title="About", user=user)

@views.route("/login", methods = ["POST", "GET"])
def login():
    form = loginForm()
    global user
    if form.is_submitted():
        user = validateUser(form.email.data, form.password.data) #get the user object from the database
        if user != None:
            return redirect(url_for("views.home"))  
        else:
            flash("Bad credentials", category="danger")
            return render_template("login.html", title="Login", form=form, user=user)    
    return render_template("login.html", title="Login", form=form, user=user)

@views.route("/logout")
def logout():
    global user
    user = None
    return redirect(url_for("views.home"))

@views.route("/login/create_account", methods = ["POST", "GET"])
def createAccount():
    form = createAccountForm()
    if form.is_submitted():
        createUser(form.userName.data, form.email.data, form.password.data)
        return redirect(url_for("views.home"))
    return render_template("createAccount.html", title="Create Accunt", form=form, user=user)

@views.route("/profile/<userID>")
def profile(userID):
    #add redirect for if user is not logged into session, redirect to log in page
    return render_template("profile.html", userID = userID, user = user)

@views.route("/staging", methods=["POST", "GET"])
def staging(): #this page is used for tecting new templates
    form = chatForm()
    return render_template("testing.html", title="Staging", form=form, user=user)

#helper methods - most of these should be moved to thier respective forms in morms.py
def validateUser(email:str, password:str) -> db.userDB:
    """
    chek the userDB for the users email. if it exists, get the users password and comepare it to the inputted passwrod.
    if the passwrod works 
    """
    try:
        user = db.session.execute(Select(db.userDB).filter_by(email=email)).scalar_one()
        # if bcrypt.check_password_hash(user.password, password):
        #     return user
        if password == user.password:
            print(f"logged in as: {user.username}")
            return user
    except:
        print("user not found")
        return None

def createUser(username:str, email:str, password:str):
    """
    This function is for adding new users to the datadase.
    Its takes in the basic information: username, email, and password.
    The funtion also add a user id and a pfp. the id is the number of curent users +1 and the initial pfp is the default pfp
    """
    try:#check if account available
        user = db.session.execute(Select(db.userDB).filter_by(email=email)).scalar_one() #this will throw an error is the email does not exist in the database
        print("user already exists")
        flash("user already created: email already associated with account.")
        return redirect(url_for('views.createAccount'))
    except:#create and add new user
        #pw_hash = bcrypt.generate_password_hash(password).decode("utf-8") #incrept the password then convert it to utf-8 string
        id = db.session.query(db.userDB).count() + 1 #the id of the new user is number of curent users +1
        #newUser = userDB(id=id, username=username, email=email, password=pw_hash, pfp="defaultPfp.jpg") #passwords should be encrypted but its being buggy rgiht now
        newUser = db.userDB(id=id, username=username, email=email, password=password, pfp="defaultPfp.jpg")
        db.session.add(newUser)
        db.session.commit()
        print("user created successfuly.")
        flash("User created successfuly.", category="info")

def deleteUser(id:int):
    user = db.session.execute(Select(db.userDB).filter_by(id=id)).scalar_one() #get the user based on thier id
    db.session.delete(user)
    db.session.commit()

def getBotResponse(modelName:str, instruction:str, knowledge:str, utterance:str) -> str:
    #set the paramaters
    #this part realy shouldnt have to be done every time, but i dont have time to make it efficient
    if modelName != None: #this is done so the feild are only updated when information is passed in
        bot.setModel(modelName)
    if knowledge != None:
        bot.setKnowledgeBase(knowledge)
    if instruction != None:
        bot.setInstruction(instruction)
    bot.readInUtterance(utterance)
    return bot.generateResponse()

def addDataToUser(knowledeg, instruction):
    if user != None and knowledeg != None and instruction != None: #make sure there is actualy data to pass into the database
        user.knowledge += knowledeg
        user.instruction = instruction

raven_website_v1/templates/about.html
{% extends "base.html" %}
{%block content %}
<div class="main-content">
    <h1>How to Use</h1>
    <p>
        The current LLM being used is GODEL, built by Microsoft in 2022. 
        There are three imput feilds: 
        The primary input feild where you may diectly message the chatbot. Raven will respond to anything you say in ths field.
        The knowledgebse feild is where you can give raven some extra knowledge. For example, Raven does not know the sky is blue by default, 
        you have to give it that information. By putting "the sky is blue" inot the knowledge base, it will now know the sky is blue.
        The third fild si where you can give it some behavioiral instruction. You can tell it to be nice or mean or talk liek it in some specific perfession.
        All feilds clear after sending a message, but you do not have to reenter the information. the last piece of the knowlegebase and instruction are held onto until more informationis given.

    </p>
    <cite>
        @misc{peng2022godel,
            author = {Peng, Baolin and Galley, Michel and He, Pengcheng and Brockett, Chris and Liden, Lars and Nouri, Elnaz and Yu, Zhou and Dolan, Bill and Gao, Jianfeng},
            title = {GODEL: Large-Scale Pre-training for Goal-Directed Dialog},
            howpublished = {arXiv},
            year = {2022},
            month = {June},
            url = {https://www.microsoft.com/en-us/research/publication/godel-large-scale-pre-training-for-goal-directed-dialog/},
            }                  
    </cite>
</div>
{% endblock %}

raven_website_v1/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{{ title }}</title>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}"> 
        <!-- bootstrap cs -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    </head>
    <body>
        <!-- bootstrap js -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        <!-- navbar -->
        <nav class="navbar navbar-expand{-sm|-md|-lg|-xl|-xxl} bg-body-secondary fixed-top">
            <div class="container-fluid">
                <a class="navbar-brand" href="{{ url_for('views.home') }}">RAVNN</a>
                <!-- justify left -->
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('views.about') }}">About</a>
                    </li>
                </ul>
                <!-- justify right -->
                <ul class="nav ms-auto">
                    <li class="nav-item">
                        {% if user != None %}
                            <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    {{ user.username }}
                                </button>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="{{ url_for('views.profile', userID = user.id) }}">Profile</a></li>
                                    <li><a class="dropdown-item" href="{{ url_for('views.logout') }}">Log out</a></li>
                                </ul>
                          </div>
                        {% else %}
                            <a class="nav-link active" aria-current="page" href="{{ url_for('views.login') }}">Login</a>
                        {% endif %}
                    </li>
                </ul> 
            </div>
        </nav>
        <!-- message flashing -->
        <div class="main-content"> <!-- main content and message container are used to so the flashed message appears in the chat window-->
            <div class="message-container">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for catagory, message in messages %}
                            <div class="alert alert-{{ catagory }}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
            </div>
        </div>
        
        <!-- this is the bock where all the other pages go -->
        {% block content %}
        
        {% endblock %}
    </body>
</html>

raven_website_v1/templates/chat.html
{% extends "base.html" %}
{%block content %}
<!-- python froms -->
{{ form.csrf_token }}
{{ form.hidden_tag() }}

<body>
<form action="#" method="post">
  <div class="sidebar">
    <h2>Sidebar</h2>
    <hr>
    <div class="input-container">
      <div class="form-group">
        {{ form.chat2.label(for="chat2", class="form-label") }}
        {{ form.chat2(id="chat2", class="form-control", placeholder="put text here")}}
      </div>
    </div>
    <div class="input-container">
      <div class="form-group">
        {{ form.chat3.label(for="chat3", class="form-label") }}
        {{ form.chat3(id="chat3", class="form-control", placeholder="put text here")}}
      </div>
    </div>
  </div>
  <div class="main-content">
    <!-- this is where the chat messages apear -->
    <div class="message-container">
      <p>
          {% for message in chatMessages %}
              <p>
                  {{ message}}
              </p>
          {% endfor %}
      </p>
    </div>
    <div class="bottom-positioned">
        <div class="input-container">
            <div class="form-floating">
                {{ form.chat1(id="chat1", class="form-control", placeholder="put text here")}}
                {{ form.chat1.label(for="chat1", class="form-label") }}
            </div>
            {{ form.submit(for="chat1", class="btn btn-primary btn-lg") }}
        </div>
    </div>
  </div>
</form>
</body>
{% endblock %}

raven_website_v1/templates/createAccount.html
{% extends "base.html" %}
{%block content %}
<div class="main-content">
    <div class="message-container">
        <h1>Ravnn Chat Create Account</h1>
        {{ form.csrf_token }}
        {{ form.hidden_tag() }}
        <form action="#" method="post"> <!-- the # means we are going to move to a completely diferent page after signing in-->
            <div class="d-grid gap-2 justify-content-md-start"> <!-- make a grid of all elements with a 2px space between each item-->    
                <div class="form-floating"> <!-- neat moving/floating efect of the feild header -->
                    {{ form.userName(id="userName", class="form-control", placeholder="raven")}}
                    {{ form.userName.label(for="userName", class="form-label") }}
                </div>
                <div class="form-floating"> <!-- neat moving/floating efect of the feild header -->
                    {{ form.email(id="email", class="form-control", placeholder="example@email.com")}}
                    {{ form.email.label(for="email", class="form-label") }}
                </div> 
                <div class="form-floating">
                    {{ form.password(id="password", class="form-control", placeholder="password1234") }}
                    {{ form.password.label(for="password", class="form-label") }}
    
                </div>
                <div class="form-floating">
                    {{ form.passowrdConfirm(id="passowrdConfirm", class="form-control", placeholder="password1234") }}
                    {{ form.passowrdConfirm.label(for="passowrdConfirm", class="form-label") }}
                </div>
                {{ form.submit(class="btn btn-primary btn-lg") }}  
            </div>
        </form>
    </div>
</div>
{% endblock %}

raven_website_v1/templates/ethansChat.html
<!DOCTYPE html>
<html>
<head>
    <title>ChatNPC</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='chat.css') }}">
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='images/smile.svg') }}">
</head>
<body>
    <div id="username-container">
        <form id="username-form">
            <div class="centered">
                <label for="username">Welcome! Please enter your username:</label><br>
                <input type="text" id="username" name="username" placeholder="Your username here"><br>
                <input type="submit" value="Submit">
            </div>
        </form>
    </div>

    <div class="main-content" id="main-content" style="display: none;">
        <div class="sidebar">
            <h2>Characters</h2>
            <ul id="character-list">
                <li data-character="caleb_brown">Caleb Brown</li>
                <li data-character="john_pebble">John Pebble</li>
                <li data-character="peter_satoru">Peter Satoru</li>
                <li data-character="melinda_deek">Melinda Deek</li>
                <li data-character="jack_mccaster">Jack McCaster</li>
                <li data-character="sarah_ratengen">Sarah Ratengen</li>
                <li data-character="evelyn_stone-brown">Evelyn Stone-Brown</li>
            </ul>
        </div>

        <div class="chat-container">
            <h1>ChatNPC</h1>
            <div id="chatbox">
                <ul id="message-list">
                    <!-- Chatbot responses and user messages will be displayed here -->
                </ul>
            </div>

            <div id="thinking-animation" style="display: none;">
                <div class="thought-bubble">
                    <div class="dot dot1"></div>
                    <div class="dot dot2"></div>
                    <div class="dot dot3"></div>
                </div>
            </div>

            <form id="chat-form">
                <div class="input-box">
                    <input type="text" id="user-input" name="user_input" disabled>
                    <input type="submit" id="send-button" value="Send" disabled>
                    <!-- <button id="run-script-button">Clean Slate Protocol</button> -->
                </div>
            </form>

            <audio autoplay id="auto-play-audio">
                <!-- Initially, the source is set to a placeholder URL; it will be updated dynamically in JavaScript -->
                <source src="" type="audio/mpeg">
                Your browser does not support the audio element.
            </audio>
        </div>
    </div>

    <div id="popup-container">
        <p id="popup-message">Select a character</p>
        <button id="close-popup-btn">X</button>
    </div>

    <!-- Include the chat.js JavaScript file -->
    <script src="{{ url_for('static', filename='chat.js') }}"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            // Add event listener to sidebar buttons
            const sidebarButtons = document.querySelectorAll('.sidebar li');
            sidebarButtons.forEach(button => {
                button.addEventListener('click', function () {
                    // Reset styles for all buttons
                    sidebarButtons.forEach(btn => {
                        btn.style.backgroundColor = '';
                        btn.style.color = '';
                    });

                    // Apply styles for clicked button
                    this.style.backgroundColor = 'white';
                    this.style.color = 'black';
                });
            });
        });
    </script> <!-- script to swap background and text colour of sidebar buttons -->
</body>
</html>

raven_website_v1/templates/login.html
{% extends "base.html" %}
{%block content %}
<div class="main-content">
    <div class="message-container">
        <h1>Ravnn Chat Login</h1>
        {{ form.csrf_token }}
        {{ form.hidden_tag() }}
        <form action="#" method="post"> <!-- the # means we are going to move to a completely diferent page after signing in-->
            <div class="d-grid gap-2 justify-content-md-start"> <!-- make a grid of all elements with a 2px space between each item-->    
                <div class="form-floating"> <!-- neat moving/floating efect of the feild header -->
                    {{ form.email(id="email", class="form-control", placeholder="example@email.com")}}
                    {{ form.email.label(for="email", class="form-label") }}
                </div> 
                <div class="form-floating">
                    {{ form.password(id="password", class="form-control", placeholder="password1234") }}
                    {{ form.password.label(for="password", class="form-label") }}
    
                </div>
                <div class="form-check"> 
                    {{ form.rememberMe(class="form-check-input") }}
                    {{ form.rememberMe.label(class="form-check-label") }}
                </div>
                {{ form.submit(class="btn btn-primary btn-lg") }}
                <button type="submit" class="btn btn-link" name="submit" value="createAccount">
                    <a href="{{ url_for('views.createAccount')}}">Create Account</a>
                </button>
            </div>
        </form>
    </div>
    
</div>
{% endblock %}

raven_website_v1/templates/profile.html
{% extends "base.html" %}
{% block title %} {{userName}} {% endblock %}
{%block content %}
<div class="main-content">
    <h2>Knowledge Base</h2>
    <hr>
    <p>{{ user.knowledge }}</p>
    <hr>
    <h2>Instructions</h2>
    <p>{{ user.instruction }}</p>
</div>
{% endblock %}

raven_website_v1/templates/testing.html
{% extends "base.html" %}
{%block content %}
<!-- python froms -->
{{ form.csrf_token }}
{{ form.hidden_tag() }}

<body>
<form action="#" method="post">
  <div class="sidebar">
    <h2>Sidebar</h2>
    <hr>
    <div class="input-container">
      <div class="form-group">
        {{ form.chat2.label(for="chat2", class="form-label") }}
        {{ form.chat2(id="chat2", class="form-control", placeholder="put text here")}}
      </div>
    </div>
    <div class="input-container">
      <div class="form-group">
        {{ form.chat3.label(for="chat3", class="form-label") }}
        {{ form.chat3(id="chat3", class="form-control", placeholder="put text here")}}
      </div>
    </div>
  </div>
  <div class="main-content">
    <!-- this is where the chat messages apear -->
    <div class="message-container">
      <p>this is where the messages will appear</p>
      <p>this is where the messages will appear</p>
      <p>this is where the messages will appear</p>
      <p>this is where the messages will appear</p>
      <p>this is where the messages will appear</p>
      <p>this is where the messages will appear</p>
      <p>this is where the messages will appear</p>
      <p>this is where the messages will appear</p>
      <p>this is where the messages will appear</p>
      <p>this is where the messages will appear</p>
      <p>this is where the messages will appear</p>
      <p>this is where the messages will appear</p>
      <p>this is where the messages will appear</p>
      <p>this is where the messages will appear</p>
      <p>this is where the messages will appear</p>
      <p>this is where the messages will appear</p>
      <p>this is where the messages will appear</p>
      <p>this is where the messages will appear</p>
      <p>this is where the messages will appear</p>
      <p>this is where the messages will appear</p>
      <p>this is where the messages will appear</p>
      <p>this is where the messages will appear</p>
      <p>this is where the messages will appear</p>
      <p>this is where the messages will appear</p>
      <p>this is where the messages will appear</p>
      <p>this is where the messages will appear</p>
      <p>this is where the messages will appear</p>
      <p>this is where the messages will appear</p>
      <p>this is where the messages will appear</p>
      <p>this is where the messages will appear</p>
      <p>this is where the messages will appear</p>
      <p>this is where the messages will appear</p>
      <p>
          {% for message in chatMessages %}
              <p>
                  {{ message}}
              </p>
          {% endfor %}
      </p>
    </div>
    <div class="bottom-positioned">
        <div class="input-container">
            <div class="form-floating">
                {{ form.chat1(id="chat1", class="form-control", placeholder="put text here")}}
                {{ form.chat1.label(for="chat1", class="form-label") }}
            </div>
            {{ form.submit(for="chat1", class="btn btn-primary btn-lg") }}
        </div>
    </div>
  </div>
</form>
</body>
{% endblock %}